/**
 * Shell-completion script generation (bash, zsh, fish).
 *
 * The generated script is derived entirely from `cli-metadata.ts` — the same
 * metadata the parser contract test checks against `parseArgs` — so adding a
 * root flag or subcommand to the metadata propagates into completions with no
 * edits here. No command names or flag names are hardcoded in this module.
 */

import { APP_NAME } from "../config.ts";
import { ROOT_FLAGS, type RootFlagMeta, type Shell, SUBCOMMANDS, type SubcommandMeta } from "./cli-metadata.ts";

export type { Shell };

const SHELLS: readonly Shell[] = ["bash", "zsh", "fish"];

export function isShell(value: string | undefined): value is Shell {
	return value === "bash" || value === "zsh" || value === "fish";
}

export function shellList(): readonly Shell[] {
	return SHELLS;
}

function flagTakesValue(flag: RootFlagMeta): boolean {
	return flag.kind !== "flag";
}

function commandTokens(c: SubcommandMeta): string[] {
	return [c.name, ...(c.aliases ?? [])];
}

/** Escape for use inside a bash double-quoted `compgen -W "…"` word list. */
function bashWords(values: readonly string[]): string {
	return values.join(" ").replace(/"/g, '\\"');
}

function bashFn(name: string): string {
	return name.replace(/[^A-Za-z0-9]/g, "_");
}

function bashValueBranch(flag: RootFlagMeta): string {
	switch (flag.kind) {
		case "flag":
		case "value":
			return "return 0";
		case "enum":
			return `COMPREPLY=( $(compgen -W "${bashWords(flag.values ?? [])}" -- "$cur") ); return 0`;
		case "list":
			return "return 0";
		case "file":
			return `COMPREPLY=( $(compgen -f -- "$cur") ); compopt -o filenames; return 0`;
		case "dir":
			return `COMPREPLY=( $(compgen -d -- "$cur") ); compopt -o filenames; return 0`;
	}
}

function bashFlagCase(flags: readonly RootFlagMeta[]): string {
	const lines: string[] = [];
	for (const f of flags) {
		if (!flagTakesValue(f)) continue;
		const labels = [`--${f.name}`, ...(f.short ? [`-${f.short}`] : [])];
		lines.push(`\t\t${labels.join("|")})\n\t\t\t${bashValueBranch(f)}\n\t\t\t;;`);
	}
	return lines.join("\n");
}

function bashFlagWords(flags: readonly RootFlagMeta[]): string {
	const words: string[] = [];
	for (const f of flags) {
		words.push(`--${f.name}`);
		if (f.short) words.push(`-${f.short}`);
	}
	return words.join(" ");
}

function generateBash(): string {
	const bin = APP_NAME;
	const parts: string[] = [];
	parts.push(`# bash completion for ${bin} — generated by \`${bin} completions bash\``);
	parts.push("");
	const subTokens = SUBCOMMANDS.flatMap(commandTokens).sort();
	parts.push(`_pi_root() {
	case "$prev" in
${bashFlagCase(ROOT_FLAGS)}
	esac
	if [[ "$cur" == -* ]]; then
		COMPREPLY=( $(compgen -W "${bashFlagWords(ROOT_FLAGS)}" -- "$cur") )
	else
		COMPREPLY=( $(compgen -W "${bashWords(subTokens)} ${bashFlagWords(ROOT_FLAGS)}" -- "$cur") )
	fi
}`);
	parts.push("");
	for (const c of SUBCOMMANDS) {
		const argEnum = c.positional && c.positional.kind === "enum" ? (c.positional.values ?? []) : [];
		const argWords = argEnum.length > 0 ? bashWords(argEnum) : "";
		const elseBranch = argWords
			? `COMPREPLY=( $(compgen -W "${argWords}" -- "$cur") )`
			: c.positional?.kind === "file"
				? `COMPREPLY=( $(compgen -f -- "$cur") ); compopt -o filenames`
				: ":";
		parts.push(`_pi_cmd_${bashFn(c.name)}() {
	if [[ "$cur" == -* ]]; then
		COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
	else
		${elseBranch}
	fi
}`);
		parts.push("");
	}
	const dispatch: string[] = [];
	for (const c of SUBCOMMANDS) {
		dispatch.push(`\t\t${commandTokens(c).join("|")})\n\t\t\t_pi_cmd_${bashFn(c.name)}\n\t\t\t;;`);
	}
	parts.push(`_pi() {
	local cur prev cmd i
	cur="\${COMP_WORDS[COMP_CWORD]}"
	prev="\${COMP_WORDS[COMP_CWORD-1]}"
	cmd=""
	for (( i=1; i < COMP_CWORD; i++ )); do
		case "\${COMP_WORDS[i]}" in
			-*) ;;
			*) cmd="\${COMP_WORDS[i]}"; break ;;
		esac
	done
	case "$cmd" in
${dispatch.join("\n")}
		*) _pi_root ;;
	esac
}
complete -F _pi ${bin}`);
	parts.push("");
	return `${parts.join("\n")}\n`;
}

/** Sanitize a description for embedding in a single-quoted zsh `_arguments` spec. */
function zshDesc(s: string): string {
	return s
		.replace(/'/g, "’")
		.replace(/\[/g, "(")
		.replace(/\]/g, ")")
		.replace(/[\r\n]+/g, " ")
		.replace(/:/g, " ")
		.trim();
}

function zshAction(flag: RootFlagMeta): string {
	switch (flag.kind) {
		case "flag":
			return "";
		case "value":
			return ":value:";
		case "enum":
			return `:value:(${(flag.values ?? []).join(" ")})`;
		case "list":
			return ":value:";
		case "file":
			return ":file:_files";
		case "dir":
			return ":dir:_files -/";
	}
}

function zshFlagSpec(f: RootFlagMeta): string {
	const body = `[${zshDesc(f.description)}]${zshAction(f)}`;
	if (f.short && f.repeatable) return `'*'{-${f.short},--${f.name}}'${body}'`;
	if (f.short) return `'(-${f.short} --${f.name})'{-${f.short},--${f.name}}'${body}'`;
	if (f.repeatable) return `'*--${f.name}${body}'`;
	return `'--${f.name}${body}'`;
}

function generateZsh(): string {
	const bin = APP_NAME;
	const parts: string[] = [];
	parts.push(`#compdef ${bin}`);
	parts.push(`# zsh completion for ${bin} — generated by \`${bin} completions zsh\``);
	parts.push("");
	const cmdRows = SUBCOMMANDS.map((c) => `\t\t'${c.name}:${zshDesc(c.description)}'`).join("\n");
	parts.push(`_pi_commands() {
	local -a commands
	commands=(
${cmdRows}
	)
	_describe -t commands 'command' commands
}`);
	parts.push("");
	for (const c of SUBCOMMANDS) {
		const positional =
			c.positional?.kind === "enum"
				? `':${c.positional.name}:(${(c.positional.values ?? []).join(" ")})'`
				: c.positional
					? `':${c.positional.name}:_files'`
					: "";
		const specs = [`'(-h --help)'{-h,--help}'[Show help]'`, positional].filter((s) => s !== "");
		parts.push(`_pi_cmd_${bashFn(c.name)}() {
	_arguments -s \\
		${specs.join(" \\\n\t\t")}
}`);
		parts.push("");
	}
	const aliasArms = SUBCOMMANDS.map((c) => `\t\t\t${commandTokens(c).join("|")}) _pi_cmd_${bashFn(c.name)} ;;`).join(
		"\n",
	);
	const rootSpecs = [
		`'(-h --help)'{-h,--help}'[Show help]'`,
		`'(-v --version)'{-v,--version}'[Show version]'`,
		...ROOT_FLAGS.filter((f) => f.name !== "help" && f.name !== "version").map(zshFlagSpec),
		`'1: :_pi_commands'`,
		`'*::arg:->args'`,
	];
	parts.push(`_pi() {
	local curcontext="$curcontext" state line
	typeset -A opt_args
	_arguments -C -s \\
		${rootSpecs.join(" \\\n\t\t")}
	case $state in
		args)
			case $line[1] in
${aliasArms}
			esac
			;;
	esac
}
# Works both ways: autoloaded from $fpath (file named _pi) or eval'd from a
# startup file. When autoloaded, funcstack[1] is _pi and we invoke it; when
# sourced/eval'd we register it with compdef instead.
if [ "$funcstack[1]" = "_pi" ]; then
	_pi "$@"
else
	compdef _pi ${bin}
fi`);
	parts.push("");
	return `${parts.join("\n")}\n`;
}

function fishDesc(s: string): string {
	return s
		.replace(/'/g, "’")
		.replace(/[\r\n]+/g, " ")
		.trim();
}

function fishValue(flag: RootFlagMeta): string {
	switch (flag.kind) {
		case "flag":
			return "";
		case "value":
			return "-x";
		case "enum":
		case "list":
			return flag.values && flag.values.length > 0 ? `-x -a '${flag.values.join(" ")}'` : "-x";
		case "file":
			return "-r -F";
		case "dir":
			return "-x -a '(__fish_complete_directories (commandline -ct))'";
	}
}

function fishFlagLine(bin: string, cond: string, f: RootFlagMeta): string {
	const segs = [`complete -c ${bin}`, `-n '${cond}'`];
	if (f.short) segs.push(`-s ${f.short}`);
	segs.push(`-l ${f.name}`);
	if (f.description) segs.push(`-d '${fishDesc(f.description)}'`);
	const val = fishValue(f);
	if (val) segs.push(val);
	return segs.join(" ");
}

function generateFish(): string {
	const bin = APP_NAME;
	const lines: string[] = [];
	lines.push(`# fish completion for ${bin} — generated by \`${bin} completions fish\``);
	lines.push("");
	const allTokens = SUBCOMMANDS.flatMap(commandTokens);
	lines.push(`function __fish_pi_no_subcommand
	for i in (commandline -opc)
		if contains -- $i ${allTokens.join(" ")}
			return 1
		end
	end
	return 0
end`);
	lines.push("");
	const rootCond = "__fish_pi_no_subcommand";
	for (const c of SUBCOMMANDS) {
		for (const token of commandTokens(c)) {
			lines.push(`complete -c ${bin} -f -n '${rootCond}' -a '${token}' -d '${fishDesc(c.description)}'`);
		}
	}
	lines.push("");
	for (const f of ROOT_FLAGS) {
		lines.push(fishFlagLine(bin, rootCond, f));
	}
	lines.push("");
	for (const c of SUBCOMMANDS) {
		const cond = `__fish_seen_subcommand_from ${commandTokens(c).join(" ")}`;
		if (c.positional?.kind === "enum") {
			lines.push(
				`complete -c ${bin} -f -n '${cond}' -a '${(c.positional.values ?? []).join(" ")}' -d '${fishDesc(c.description)}'`,
			);
		} else if (c.positional?.kind === "file") {
			lines.push(`complete -c ${bin} -F -n '${cond}'`);
		}
	}
	lines.push("");
	return `${lines.join("\n")}\n`;
}

export function generateCompletion(shell: Shell): string {
	switch (shell) {
		case "bash":
			return generateBash();
		case "zsh":
			return generateZsh();
		case "fish":
			return generateFish();
	}
}
