import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

const REPO_ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const INSTALL_SH = join(REPO_ROOT, "scripts", "install.sh");
const PKG_VERSION = JSON.parse(
	readFileSync(join(REPO_ROOT, "packages", "coding-agent", "package.json"), "utf8"),
).version;

// install.sh is POSIX sh. On Windows we drive it through the msys2 bash if one
// is installed; otherwise the shell-leg tests are skipped with a clear reason.
function shRunner() {
	if (process.platform !== "win32") {
		return { command: "sh", prefix: [] };
	}
	const candidates = ["C:\\msys64\\usr\\bin\\bash.exe", "C:\\Program Files\\Git\\bin\\bash.exe"];
	for (const candidate of candidates) {
		if (existsSync(candidate)) {
			return { command: candidate, prefix: [INSTALL_SH.replaceAll("\\", "/").replace(/^([A-Za-z]):/, "/$1").toLowerCase()] };
		}
	}
	return null;
}

const runner = shRunner();
const hasNodePath = (() => {
	if (!runner) return false;
	const probe = runner.command === "sh" ? ["sh", "-c", "command -v node"] : [runner.command, "-lc", "command -v node || ls '/c/Program Files/nodejs/node.exe'"];
	const result = spawnSync(probe[0], probe.slice(1), { encoding: "utf8" });
	return result.status === 0 && result.stdout.trim().length > 0;
})();

function runInstall(args, { input, sandbox }) {
	const scriptArg =
		runner.command === "sh"
			? INSTALL_SH
			: INSTALL_SH.replaceAll("\\", "/").replace(/^([A-Za-z]):/, "/$1").toLowerCase();
	const env = {
		...process.env,
		HOME: sandbox,
		PI_CODING_AGENT_DIR: join(sandbox, "agent"),
		PI_INSTALL_DIR: join(sandbox, "bin"),
		XDG_CONFIG_HOME: join(sandbox, "config"),
		NODE_OPTIONS: "",
	};
	if (process.platform === "win32") {
		// The shim embeds node by name; put the Windows node dir on PATH.
		const nodeDir = join(process.execPath, "..");
		env.PATH = `${nodeDir};${process.env.PATH}`;
	}
	const command = runner.command === "sh" ? "sh" : runner.command;
	const argv =
		runner.command === "sh"
			? [scriptArg, ...args]
			: ["-lc", `export PATH="${String(join(process.execPath, "..")).replaceAll("\\", "/").replace(/^([A-Za-z]):/, "/$1")}:$PATH"; sh "${scriptArg}" ${args.map((a) => `"${a}"`).join(" ")}`];
	const result = spawnSync(command, argv, { input, encoding: "utf8", env, timeout: 300_000 });
	return result;
}

function makeSandbox(t) {
	const dir = join(tmpdir(), `pi-install-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
	mkdirSync(join(dir, "bin"), { recursive: true });
	mkdirSync(join(dir, "agent", "sessions"), { recursive: true });
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	return dir;
}

test("A04: unknown option fails with usage", { skip: !runner }, () => {
	const sandbox = join(tmpdir(), `pi-install-test-unknown-${Date.now()}`);
	mkdirSync(sandbox, { recursive: true });
	try {
		const result = runInstall(["--frobnicate"], { sandbox });
		assert.equal(result.status, 1);
		assert.match(result.stderr, /Unknown option/);
	} finally {
		rmSync(sandbox, { recursive: true, force: true });
	}
});

test("A05: install exits non-zero when the installed launcher cannot report a version", { skip: !runner }, () => {
	// --version with a bogus explicit tag exercises the online path error
	// handling; this only asserts the flag is parsed and routed.
	const sandbox = join(tmpdir(), `pi-install-test-badver-${Date.now()}`);
	mkdirSync(sandbox, { recursive: true });
	try {
		const result = runInstall(["--binary", "--version", "v0.0.0-does-not-exist"], { sandbox });
		assert.equal(result.status, 1);
		assert.doesNotMatch(result.stdout, /Installed: pi/);
	} finally {
		rmSync(sandbox, { recursive: true, force: true });
	}
});

test("A03/A05/A06: source install from the archive works offline and prints the real version", { skip: !runner || !hasNodePath }, (t) => {
	const sandbox = makeSandbox(t);
	const result = runInstall(["--source"], { sandbox });
	assert.equal(result.status, 0, result.stderr);
	// A05: the success line must be the real `pi --version` output, not a placeholder.
	assert.match(result.stdout, new RegExp(`Installed: pi ${PKG_VERSION.replace(/\./g, "\\.")}`));
	// A06: completion files were generated by the installed launcher itself.
	assert.ok(existsSync(join(sandbox, ".bash_completion.d", "pi")), "bash completion installed");
	assert.ok(existsSync(join(sandbox, ".zsh", "completions", "_pi")), "zsh completion installed");
	assert.ok(existsSync(join(sandbox, "config", "fish", "completions", "pi.fish")), "fish completion installed");
	const bashCompletion = readFileSync(join(sandbox, ".bash_completion.d", "pi"), "utf8");
	assert.match(bashCompletion, /complete -F/);
	assert.match(bashCompletion, /install/);
});

test("A04/B08: uninstall aborts on decline and preserves user data", { skip: !runner || !hasNodePath }, (t) => {
	const sandbox = makeSandbox(t);
	writeFileSync(join(sandbox, "agent", "settings.json"), JSON.stringify({ theme: "dark" }));
	writeFileSync(join(sandbox, "agent", "credential.json"), "TOKEN=abc");
	writeFileSync(join(sandbox, "agent", "sessions", "s1.jsonl"), "{}\n");
	const install = runInstall(["--source"], { sandbox });
	assert.equal(install.status, 0, install.stderr);

	const decline = runInstall(["--uninstall"], { input: "n\n", sandbox });
	assert.equal(decline.status, 1);
	assert.match(decline.stdout, /Uninstall aborted/);
	assert.ok(existsSync(join(sandbox, "bin", process.platform === "win32" ? "pi.cmd" : "pi")) || existsSync(join(sandbox, "bin", "pi")));
});

test("A04/B08: uninstall with confirmation removes only installer artifacts and says so", {
	skip: !runner || !hasNodePath,
}, (t) => {
	const sandbox = makeSandbox(t);
	writeFileSync(join(sandbox, "agent", "settings.json"), JSON.stringify({ theme: "dark" }));
	writeFileSync(join(sandbox, "agent", "credential.json"), "TOKEN=abc");
	writeFileSync(join(sandbox, "agent", "sessions", "s1.jsonl"), "{}\n");
	const install = runInstall(["--source"], { sandbox });
	assert.equal(install.status, 0, install.stderr);

	const confirm = runInstall(["--uninstall"], { input: "y\n", sandbox });
	assert.equal(confirm.status, 0, confirm.stderr);
	assert.match(confirm.stdout, /preserved/);
	assert.match(confirm.stdout, /NOT removed/);
	// B08: user data survives.
	assert.ok(existsSync(join(sandbox, "agent", "settings.json")));
	assert.ok(existsSync(join(sandbox, "agent", "credential.json")));
	assert.ok(existsSync(join(sandbox, "agent", "sessions", "s1.jsonl")));
	// The launcher and generated completions are gone.
	assert.ok(!existsSync(join(sandbox, "bin", "pi")) && !existsSync(join(sandbox, "bin", "pi.cmd")));
	assert.ok(!existsSync(join(sandbox, ".bash_completion.d", "pi")));
});
