// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/nebius.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const NEBIUS_MODELS: ChatModelCatalog<typeof values, "nebius"> =
	flattenChatModelCatalog("nebius", values);

export const NEBIUS_IMAGE_MODELS: ImageModelCatalog<typeof values, "nebius"> =
	flattenImageModelCatalog("nebius", values);

export const NEBIUS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "nebius"> =
	flattenClassifierModelCatalog("nebius", values);
